### ISSUE TITLE
ConfusionMatrix:render() bug

### ISSUE THREAD

**Issue by gcheron** [torch/optim#70]
This is related to pull request #63 : https://github.com/torch/optim/pull/63

There are many divisions happening in the render function. 
The rendered image is full of zeros because in the self.mat LongTensor, everything is rounded down to zero after dividing by the number of samples.

That commit should be reverted...

@soumith 
@jonathantompson

**Comment by soumith** [comment]
thanks, reverted.

**Comment by jonathantompson** [comment]
Sorry, I didn't check the render function.  I never use it (does anyone really?), so I didn't look it over.

OK, now my apologies are out of the way...reverting the change is a little weird.  It fixed an ACTUAL bug, namely the accumulator overflows very quickly with large batch sizes, resulting in completely wrong confusion matrices.  Instead of reverting an actual bug fix, why are we not fixing the render function (which very few people use).  It could have even been a dumb one line change (convert the confusion matrix to double before rendering it), I would even be happy with having a double accumulator (rather than Long).

**Comment by soumith** [comment]
Will fix properly in a bit

**Comment by soumith** [comment]
@jonathantompson sorry for the delay, fixed now to integrate both fixes.
